name: new_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image_picker: ^0.8.4+4
  permission_handler: ^10.2.0
  pie_chart: ^5.0.0
  url_launcher: ^6.0.17
  geolocator: ^9.0.2
  geocoding: ^2.0.0
  cupertino_icons: ^1.0.6
  provider: ^6.0.4  # Corrected indentation
  shared_preferences: ^2.3.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Luna
      fonts:
        - asset: assets/fonts/Luna.ttf
